[urgency_low]
    background = "#6f2993"
    foreground = "#4d217b"

[urgency_normal]
    background = "#7e489c"
    foreground = "#9b9097"

[urgency_critical]
    background = "#513080"
    foreground = "#6f2993"
