set -g default-terminal "xterm-256color"
setw -g mode-keys vi

# Change prefix to C-a
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# vim-like window navigation
bind-key t next-window
bind-key T previous-window
bind-key C-o rotate-window

# vim-like plane splitting
unbind-key |
bind-key v split-window -h
unbind-key %
bind-key s split-window -v
unbind-key o
bind-key -r w select-pane -t :.+

# vim-like pane resizing  
bind-key -r C-k resize-pane -U
bind-key -r C-j resize-pane -D
bind-key -r C-h resize-pane -L
bind-key -r C-l resize-pane -R

# vim-like pane switching
bind-key -r k select-pane -U 
bind-key -r j select-pane -D 
bind-key -r h select-pane -L 
bind-key -r l select-pane -R 

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Mouse on
setw -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'dracula/tmux'

# Set Dracula options
set -g @dracula-show-powerline true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
