# Configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
duid

# Persist interface configuration when dhcpcd exits.
persistent

# vendorclassid is set to blank to avoid sending the default of
vendorclassid

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search
option classless_static_routes
option interface_mtu

# Rapid commit support.
option rapid_commit

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate Stable Private IPv6 Addresses based from the DUID
slaac private
# Don't attempt to obtain an IPv4LL address if we failed to get one via DHCP.  See RFC 3927.
noipv4ll

# Static profile
interface enp3s0 
static ip_address=192.168.1.6/24	
static routers=192.168.1.254
static domain_name_servers=192.168.1.254 8.8.8.8

