# Configuration file for dnsmasq.
#
# Format is one option per line, legal options are the same
# as the long options legal on the command line. See
# "/usr/sbin/dnsmasq --help" or "man 8 dnsmasq" for details.

# Never forward plain names (without a dot or domain part)
domain-needed

# Never forward addresses in the non-routed address spaces.
bogus-priv

# Set the cachesize here.
cache-size=1000

# Add domains which you want to force to an IP address here.
address=/romualdrousseau.is-a-geek.org/192.168.1.200
