# Defaull fish variables
# Generated by 'wal'
fish_color_normal normal --theme=wal
fish_color_command {color1.strip} --theme=wal
fish_color_param {color5.strip} --theme=wal
fish_color_redirection {color5.strip} --theme=wal
fish_color_comment {color8.strip} --theme=wal
fish_color_error ff0000 --theme=wal
fish_color_escape {color5.strip} --theme=wal
fish_color_operator {color5.strip} --theme=wal
fish_color_end {color2.strip} --theme=wal
fish_color_quote {color2.strip} --theme=wal
fish_color_autosuggestion 555 brblack --theme=wal
fish_color_user brgreen --theme=wal
fish_color_host normal --theme=wal
fish_color_valid_path --underline --theme=wal
fish_color_cwd green --theme=wal
fish_color_cwd_root red --theme=wal
fish_color_match --background=brblu --theme=wale
fish_color_search_match bryellow --background=brblack --theme=wal
fish_color_selection white --bold --background=brblack --theme=wal
fish_color_cancel -r --theme=wal
fish_pager_color_prefix white --bold --underline --theme=wal
fish_pager_color_completion --theme=wal
fish_pager_color_description {color2.strip} yellow --theme=wal
fish_pager_color_progress brwhite --background=cyan --theme=wal
fish_color_history_current --bold --theme=wal

# Wallpaper
fish_color_wallpaper {wallpaper} --theme=wal

# Colors
fish_color_color1 {color1.strip} --theme=wal
fish_color_color2 {color2.strip} --theme=wal
fish_color_color3 {color3.strip} --theme=wal
fish_color_color4 {color4.strip} --theme=wal
fish_color_color5 {color5.strip} --theme=wal
fish_color_color6 {color6.strip} --theme=wal
fish_color_color7 {color7.strip} --theme=wal
fish_color_color8 {color8.strip} --theme=wal
fish_color_color9 {color9.strip} --theme=wal
fish_color_color10 {color10.strip} --theme=wal
fish_color_color11 {color11.strip} --theme=wal
fish_color_color12 {color12.strip} --theme=wal
fish_color_color13 {color13.strip} --theme=wal
fish_color_color14 {color14.strip} --theme=wal
fish_color_color15 {color15.strip} --theme=wal

