# Defaull fish variables
# Generated by 'wal'
set -U fish_color_normal normal
set -U fish_color_command {color1.strip}
set -U fish_color_param {color5.strip}
set -U fish_color_redirection $fish_color_param
set -U fish_color_comment {color8.strip}
set -U fish_color_error ff0000
set -U fish_color_escape {color5.strip}
set -U fish_color_operator $fish_color_escape
set -U fish_color_end {color2.strip}
set -U fish_color_quote {color2.strip}
set -U fish_color_autosuggestion 555 brblack
set -U fish_color_user brgreen
set -U fish_color_host $fish_color_normal
set -U fish_color_valid_path --underline
set -U fish_color_cwd green
set -U fish_color_cwd_root red
set -U fish_color_match --background=brblue
set -U fish_color_search_match bryellow --background=brblack
set -U fish_color_selection white --bold --background=brblack
set -U fish_color_cancel -r
set -U fish_pager_color_prefix white --bold --underline
set -U fish_pager_color_completion
set -U fish_pager_color_description $fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold

# Wallpaper
set -U fish_color_wallpaper {wallpaper}

# Colors
set -U fish_color_color1 {color1.strip}
set -U fish_color_color2 {color2.strip}
set -U fish_color_color3 {color3.strip}
set -U fish_color_color4 {color4.strip}
set -U fish_color_color5 {color5.strip}
set -U fish_color_color6 {color6.strip}
set -U fish_color_color7 {color7.strip}
set -U fish_color_color8 {color8.strip}
set -U fish_color_color9 {color9.strip}
set -U fish_color_color10 {color10.strip}
set -U fish_color_color11 {color11.strip}
set -U fish_color_color12 {color12.strip}
set -U fish_color_color13 {color13.strip}
set -U fish_color_color14 {color14.strip}
set -U fish_color_color15 {color15.strip}

