# Shell variables
# Generated by 'wal'
wallpaper='/home/test/.local/share/wallpapers/wallpaper.jpg'

# Special
background='#150c11'
foreground='#d9cbd1'
cursor='#d9cbd1'

# Colors
color0='#150c11'
color1='#672CA5'
color2='#6D41AB'
color3='#9766AD'
color4='#9537C5'
color5='#A860D1'
color6='#2DD1BD'
color7='#d9cbd1'
color8='#978e92'
color9='#672CA5'
color10='#6D41AB'
color11='#9766AD'
color12='#9537C5'
color13='#A860D1'
color14='#2DD1BD'
color15='#d9cbd1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
