[colors.primary]
background = "#200e18"
foreground = "#c7c2c5"

[colors.cursor]
text = "#200e18"
cursor = "#c7c2c5"

[colors.vi_mode_cursor]
text = "#200e18"
cursor = "#c7c2c5"

[colors.search.matches]
foreground = "#200e18"
background = "#c7c2c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#7d6671"
background = "#9b9097"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#200e18"
red = "#903de7"
green = "#854ed1"
yellow = "#875b9b"
blue = "#9f3ad2"
magenta = "#8f52b1"
cyan = "#219c8d"
white = "#9b9097"

[colors.bright]
black = "#7d6671"
red = "#903ee7"
green = "#854fd1"
yellow = "#9766AD"
blue = "#9f3ad2"
magenta = "#A860D1"
cyan = "#2DD1BD"
white = "#c7c2c5"

[colors.dim]
black = "#c7c2c5"
red = "#903ee7"
green = "#A860D1"
yellow = "#9766AD"
blue = "#9f3ad2"
magenta = "#854fd1"
cyan = "#2DD1BD"
white = "#7d6671"

