[colors]
background = '#200e188e'
black = '#200e18'
blue = '#903de7'
cursor = '#c7c2c5'
cyan = '#854ed1'
foreground = '#c7c2c5'
green = '#875b9b'
magenta = '#9f3ad2'
red = '#8f52b1'
tabs = '#c7c2c5'
tabs-active = '#219c8d'
white = '#c7c2c5'
yellow = '#9b9097'
dim-black = '#200e188e'
dim-blue = '#903de78e'
dim-cyan = '#854ed18e'
dim-foreground = '#c7c2c58e'
dim-green = '#875b9b8e'
dim-magenta = '#9f3ad28e'
dim-red = '#8f52b18e'
dim-white = '#219c8d8e'
dim-yellow = '#9b90978e'
light-black = '#903ee7'
light-blue = '#854fd1'
light-cyan = '#9766AD'
light-foreground = '#9f3ad2'
light-green = '#A860D1'
light-magenta = '#2DD1BD'
light-red = '#c7c2c5'
light-white = '#903ee7'
light-yellow = '#854fd1'
