--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/test/.local/share/wallpapers/wallpaper.jpg"

-- Special
background="#200e18"
foreground="#c7c2c5"
cursor="#c7c2c5"

-- Colors
color0="#200e18"
color1="#903de7"
color2="#854ed1"
color3="#875b9b"
color4="#9f3ad2"
color5="#8f52b1"
color6="#219c8d"
color7="#9b9097"
color8="#7d6671"
color9="#903ee7"
color10="#854fd1"
color11="#9766AD"
color12="#9f3ad2"
color13="#A860D1"
color14="#2DD1BD"
color15="#c7c2c5"
