foreground         #c7c2c5
background         #200e18
background_opacity 1.0
cursor             #c7c2c5

active_tab_foreground     #200e18
active_tab_background     #c7c2c5
inactive_tab_foreground   #c7c2c5
inactive_tab_background   #200e18

active_border_color   #c7c2c5
inactive_border_color #200e18
bell_border_color     #903de7

color0       #200e18
color8       #7d6671
color1       #903de7
color9       #903ee7
color2       #854ed1
color10      #854fd1
color3       #875b9b
color11      #9766AD
color4       #9f3ad2
color12      #9f3ad2
color5       #8f52b1
color13      #A860D1
color6       #219c8d
color14      #2DD1BD
color7       #9b9097
color15      #c7c2c5
