foreground   #d9cbd1
background   #150c11
cursor       #d9cbd1

color0       #150c11
color8       #978e92
color1       #672CA5
color9       #672CA5
color2       #6D41AB
color10      #6D41AB
color3       #9766AD
color11      #9766AD
color4       #9537C5
color12      #9537C5
color5       #A860D1
color13      #A860D1
color6       #2DD1BD
color14      #2DD1BD
color7       #d9cbd1
color15      #d9cbd1
