# Defaull fish variables
# Generated by 'wal'
set -U fish_color_normal normal
set -U fish_color_command 672CA5
set -U fish_color_param A860D1
set -U fish_color_redirection $fish_color_param
set -U fish_color_comment 978e92
set -U fish_color_error ff0000
set -U fish_color_escape A860D1
set -U fish_color_operator $fish_color_escape
set -U fish_color_end 6D41AB
set -U fish_color_quote 6D41AB
set -U fish_color_autosuggestion 555 brblack
set -U fish_color_user brgreen
set -U fish_color_host $fish_color_normal
set -U fish_color_valid_path --underline
set -U fish_color_cwd green
set -U fish_color_cwd_root red
set -U fish_color_match --background=brblue
set -U fish_color_search_match bryellow --background=brblack
set -U fish_color_selection white --bold --background=brblack
set -U fish_color_cancel -r
set -U fish_pager_color_prefix white --bold --underline
set -U fish_pager_color_completion
set -U fish_pager_color_description $fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold

# Wallpaper
set -U fish_color_wallpaper /home/test/.local/share/wallpapers/wallpaper.jpg

# Colors
set -U fish_color_color1 672CA5
set -U fish_color_color2 6D41AB
set -U fish_color_color3 9766AD
set -U fish_color_color4 9537C5
set -U fish_color_color5 A860D1
set -U fish_color_color6 2DD1BD
set -U fish_color_color7 d9cbd1
set -U fish_color_color8 978e92
set -U fish_color_color9 672CA5
set -U fish_color_color10 6D41AB
set -U fish_color_color11 9766AD
set -U fish_color_color12 9537C5
set -U fish_color_color13 A860D1
set -U fish_color_color14 2DD1BD
set -U fish_color_color15 d9cbd1

