# Defaull fish variables
# Generated by 'wal'
set -U fish_color_normal normal
set -U fish_color_command 903de7
set -U fish_color_param 8f52b1
set -U fish_color_redirection $fish_color_param
set -U fish_color_comment 7d6671
set -U fish_color_error ff0000
set -U fish_color_escape 8f52b1
set -U fish_color_operator $fish_color_escape
set -U fish_color_end 854ed1
set -U fish_color_quote 854ed1
set -U fish_color_autosuggestion 555 brblack
set -U fish_color_user brgreen
set -U fish_color_host $fish_color_normal
set -U fish_color_valid_path --underline
set -U fish_color_cwd green
set -U fish_color_cwd_root red
set -U fish_color_match --background=brblue
set -U fish_color_search_match bryellow --background=brblack
set -U fish_color_selection white --bold --background=brblack
set -U fish_color_cancel -r
set -U fish_pager_color_prefix white --bold --underline
set -U fish_pager_color_completion
set -U fish_pager_color_description $fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold

# Wallpaper
set -U fish_color_wallpaper /home/test/.local/share/wallpapers/wallpaper.jpg

# Colors
set -U fish_color_color1 903de7
set -U fish_color_color2 854ed1
set -U fish_color_color3 875b9b
set -U fish_color_color4 9f3ad2
set -U fish_color_color5 8f52b1
set -U fish_color_color6 219c8d
set -U fish_color_color7 9b9097
set -U fish_color_color8 7d6671
set -U fish_color_color9 903ee7
set -U fish_color_color10 854fd1
set -U fish_color_color11 9766AD
set -U fish_color_color12 9f3ad2
set -U fish_color_color13 A860D1
set -U fish_color_color14 2DD1BD
set -U fish_color_color15 c7c2c5

