--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/test/.local/share/wallpapers/wallpaper.jpg"

-- Special
background="#150c11"
foreground="#d9cbd1"
cursor="#d9cbd1"

-- Colors
color0="#150c11"
color1="#672CA5"
color2="#6D41AB"
color3="#9766AD"
color4="#9537C5"
color5="#A860D1"
color6="#2DD1BD"
color7="#d9cbd1"
color8="#978e92"
color9="#672CA5"
color10="#6D41AB"
color11="#9766AD"
color12="#9537C5"
color13="#A860D1"
color14="#2DD1BD"
color15="#d9cbd1"
