# Shell variables
# Generated by 'wal'
wallpaper="/home/test/.local/share/wallpapers/wallpaper.jpg"

# Special
background='#200e18'
foreground='#c7c2c5'
cursor='#c7c2c5'

# Colors
color0='#200e18'
color1='#903de7'
color2='#854ed1'
color3='#875b9b'
color4='#9f3ad2'
color5='#8f52b1'
color6='#219c8d'
color7='#9b9097'
color8='#7d6671'
color9='#903ee7'
color10='#854fd1'
color11='#9766AD'
color12='#9f3ad2'
color13='#A860D1'
color14='#2DD1BD'
color15='#c7c2c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
