# pywal theme for ghostty

background = 200e18
foreground = c7c2c5
cursor-color = c7c2c5
selection-background = c7c2c5
selection-foreground = 200e18

palette = 0=#200e18
palette = 1=#903de7
palette = 2=#854ed1
palette = 3=#875b9b
palette = 4=#9f3ad2
palette = 5=#8f52b1
palette = 6=#219c8d
palette = 7=#9b9097
palette = 8=#7d6671
palette = 9=#903ee7
palette = 10=#854fd1
palette = 11=#9766AD
palette = 12=#9f3ad2
palette = 13=#A860D1
palette = 14=#2DD1BD
palette = 15=#c7c2c5
